version: 3.0.2.{build}

# branches to build
branches:
  only:
  - master
  - dev

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
  - x64

configuration:
  - Release

# clone directory
clone_folder: c:\dev\RECore

# scripts that run after cloning repository
install:
  - cd c:\dev\RECore
  - md RECore-install-dir
  - git submodule update --init --recursive

build:

build_script:
  - cd c:\dev\RECore
  - md build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\RECore\RECore-install-dir -DCMAKE_BUILD_TYPE=Release -DRECORE_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% ..
  - cmake --build . --config Release
  - cmake --build . --config Release --target INSTALL
#  - ctest

after_build:

test_script:
